server:
  port: 3002
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://www.eureka3000.com:3000/eureka,http://www.eureka3001.com:3001/eureka


